### ISSUE TITLE
Implementin this configuration

### ISSUE THREAD

**Issue by kascesar** [zzkt/crkbd#1]
Hi i got this error when:
`qmk compile -kb crkbd -km zzkt4`

and got:

`Ψ Compiling keymap with make --jobs=1 crkbd/rev1:zzkt4

QMK Firmware 0.15.13
Making crkbd/rev1 with keymap zzkt4

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/crkbd/crkbd.c                                                                  [OK]
Compiling: keyboards/crkbd/rev1/rev1.c                                                              [OK]
Compiling: keyboards/crkbd/keymaps/zzkt4/keymap.c                                                  keyboards/crkbd/keymaps/zzkt4/keymap.c:7:48: error: redeclaration of enumerator ‘MACRO_13’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:580:5: note: previous definition of ‘MACRO_13’ was here
     MACRO_13,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:58: error: redeclaration of enumerator ‘MACRO_12’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                          ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:579:5: note: previous definition of ‘MACRO_12’ was here
     MACRO_12,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:68: error: redeclaration of enumerator ‘MACRO_11’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                    ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:578:5: note: previous definition of ‘MACRO_11’ was here
     MACRO_11,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:78: error: redeclaration of enumerator ‘MACRO_10’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                              ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:577:5: note: previous definition of ‘MACRO_10’ was here
     MACRO_10,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:88: error: redeclaration of enumerator ‘MACRO_9’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                        ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:576:5: note: previous definition of ‘MACRO_9’ was here
     MACRO_9,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:97: error: redeclaration of enumerator ‘MACRO_8’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                 ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:575:5: note: previous definition of ‘MACRO_8’ was here
     MACRO_8,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:106: error: redeclaration of enumerator ‘MACRO_7’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                          ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:574:5: note: previous definition of ‘MACRO_7’ was here
     MACRO_7,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:115: error: redeclaration of enumerator ‘MACRO_6’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                                   ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:573:5: note: previous definition of ‘MACRO_6’ was here
     MACRO_6,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:124: error: redeclaration of enumerator ‘MACRO_5’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                                            ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:572:5: note: previous definition of ‘MACRO_5’ was here
     MACRO_5,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:133: error: redeclaration of enumerator ‘MACRO_4’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                                                     ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:571:5: note: previous definition of ‘MACRO_4’ was here
     MACRO_4,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:142: error: redeclaration of enumerator ‘MACRO_3’
       enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2
                                                                                                                                              ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:570:5: note: previous definition of ‘MACRO_3’ was here
     MACRO_3,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:151: error: redeclaration of enumerator ‘MACRO_2’
   enum custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2, MA
                                                                                                                                                   ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:569:5: note: previous definition of ‘MACRO_2’ was here
     MACRO_2,
     ^
keyboards/crkbd/keymaps/zzkt4/keymap.c:7:160: error: redeclaration of enumerator ‘MACRO_1’
 custom_keycodes {EPRM = SAFE_RANGE, MACRO_13, MACRO_12, MACRO_11, MACRO_10, MACRO_9, MACRO_8, MACRO_7, MACRO_6, MACRO_5, MACRO_4, MACRO_3, MACRO_2, MACRO_1};
                                                                                                                                                     ^
In file included from quantum/keymap.h:47:0,
                 from quantum/quantum.h:21,
                 from keyboards/crkbd/rev1/rev1.h:22,
                 from keyboards/crkbd/crkbd.h:21,
                 from keyboards/crkbd/keymaps/zzkt4/keymap.c:3:
quantum/quantum_keycodes.h:568:5: note: previous definition of ‘MACRO_1’ was here
     MACRO_1,
     ^
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:457: .build/obj_crkbd_rev1_zzkt4/keyboards/crkbd/keymaps/zzkt4/keymap.o] Error 1
make: *** [Makefile:478: crkbd/rev1:zzkt4] Error 1
Make finished with errors`

Any suggestions ? thanks a lot! :D

**Comment by zzkt** [comment]
did you work it out @kascesar ? i just tried building with a newer qmk and get the same error. looks like the macros are now defined in `quantum/quantum_keycodes.h` so you should be able to comment out the `enum custom_keycodes ...` section in `zzkt4/keymap.c` for it to work.

**Comment by kascesar** [comment]
yep now it works, thanks a lot :D!!!
